# Inserts a blank line between shell prompts
format = """
[┌─](bold white) $time
[│](bold white)$all"""

# add_newline = false
command_timeout = 1000

# Replace the "❯" symbol in the prompt with "➜"
[character]
format = """$symbol """
success_symbol = "[➜](bold green)"
error_symbol = "[](bold red)"

[[battery.display]]
threshold = -1
style = 'bold red'

[cmd_duration]
min_time = 5000
format = "took [$duration](bold yellow)"

[git_metrics]
disabled = false

[time]
disabled = false
use_12hr = true
format = "[$time](bold yellow)"

[aws]
symbol = "  "
style = "208"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
style = "11"

[directory.substitutions]
"com~apple~CloudDocs" = "/iCloud"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nodejs]
style = "34"

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "blue"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "



